package lucas.graeff.sportsapp.models

import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import kotlinx.parcelize.RawValue

@Parcelize
data class Player(
    val dateBorn: String,
    val dateSigned: @RawValue Any,
    val idAPIfootball: @RawValue Any,
    val idPlayer: String,
    val idPlayerManager: @RawValue Any,
    val idSoccerXML: @RawValue Any,
    val idTeam: String,
    val idTeam2: String,
    val idTeamNational: @RawValue Any,
    val intLoved: String,
    val intSoccerXMLTeamID: @RawValue Any,
    val strAgent: String,
    val strBanner: @RawValue Any,
    val strBirthLocation: String,
    val strCollege: @RawValue Any,
    val strCreativeCommons: String,
    val strCutout: String,
    val strDescriptionCN: @RawValue Any,
    val strDescriptionDE: @RawValue Any,
    val strDescriptionEN: String,
    val strDescriptionES: @RawValue Any,
    val strDescriptionFR: @RawValue Any,
    val strDescriptionHU: @RawValue Any,
    val strDescriptionIL: @RawValue Any,
    val strDescriptionIT:  @RawValue Any,
    val strDescriptionJP: @RawValue Any,
    val strDescriptionNL: @RawValue Any,
    val strDescriptionNO: @RawValue Any,
    val strDescriptionPL: @RawValue Any,
    val strDescriptionPT: @RawValue Any,
    val strDescriptionRU: @RawValue Any,
    val strDescriptionSE: @RawValue Any,
    val strFacebook: String,
    val strFanart1: String,
    val strFanart2: @RawValue Any,
    val strFanart3: @RawValue Any,
    val strFanart4: @RawValue Any,
    val strGender: String,
    val strHeight: String,
    val strInstagram: String,
    val strKit: String,
    val strLocked: String,
    val strNationality: String,
    val strNumber: String,
    val strOutfitter: String,
    val strPlayer: String,
    val strPlayerAlternate: @RawValue Any,
    val strPosition: String,
    val strRender: String,
    val strSide: String,
    val strSigning: String,
    val strSport: String,
    val strTeam: String,
    val strTeam2: String,
    val strThumb: String,
    val strTwitter: String,
    val strWage: String,
    val strWebsite: String,
    val strWeight: String,
    val strYoutube: String
) : Parcelable